<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-A8BL1MV" failures="1" tests="10" name="Test" time="0.12" errors="0" timestamp="11 Nov 2020 18:04:49 GMT">
  <testcase classname="org.rerun.TestCase" name="method1" time="0.013"/>
  <testcase classname="org.rerun.TestCase" name="method2" time="0.002"/>
  <testcase classname="org.rerun.TestCase" name="method3" time="0.003"/>
  <testcase classname="org.rerun.TestCase" name="method4" time="0.008">
    <skipped/>
  </testcase> <!-- method4 -->
  <testcase classname="org.rerun.TestCase" name="method4" time="0.002">
    <skipped/>
  </testcase> <!-- method4 -->
  <testcase classname="org.rerun.TestCase" name="method4" time="0.001">
    <skipped/>
  </testcase> <!-- method4 -->
  <testcase classname="org.rerun.TestCase" name="method4" time="0.002">
    <skipped/>
  </testcase> <!-- method4 -->
  <testcase classname="org.rerun.TestCase" name="method4" time="0.002">
    <skipped/>
  </testcase> <!-- method4 -->
  <testcase classname="org.rerun.TestCase" name="method4" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.TestCase.method4(TestCase.java:22)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method4 -->
  <testcase classname="org.rerun.TestCase" name="method5" time="0.003"/>
</testsuite> <!-- Test -->
